spring:
  application:
    name: hospitalManagement

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/hospitalDb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update   # ?? use update instead of create in Docker
    show-sql: true
    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    context-path: /api/v1